apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 1password.yaml
  - service.yaml
  - deployment.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - rolebinding.yaml
  - namespace.yaml
  - applications.fintlabs.no-v1.yml