apiVersion: v1
kind: ServiceAccount
metadata:
  name: flaiserator
  labels:
    app.kubernetes.io/name: flaiserator
    app.kubernetes.io/instance: flais-flaiserator
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: GA
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: fintlabs-application-infrastructure-services
    fintlabs.no/team: flais