apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value: 
          name: "fint.unleash.api"
          value: "https://unleash-alpha.fintlabs.no/api/"
    target:
      kind: Deployment
      name: flaiserator

