apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/env/1/name"
        value: "https://unleash-alpha.fintlabs.no/api/"
    target:
      kind: Deployment
      name: flaiserator

