{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "flaiserator.fullname" . }}
  labels:
    {{- include "flaiserator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flaiserator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "flaiserator.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
{{- end }}