apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "flaiserator.fullname" . }}-prometheus
  labels:
    {{- include "flaiserator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "flaiserator.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
  policyTypes:
    - Ingress