apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "flaiserator.labels" . | nindent 4 }}
  name: {{ include "flaiserator.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "flaiserator.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics