name: .app-build.yaml

on:
  workflow_call:
    outputs:
      image-tag:
        description: "Docker image tag"
        value: ${{ jobs.build-and-publish.outputs.image-tag }}

jobs:
  build-and-publish:
    name: Build & Publish Docker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      image-tag: ${{ steps.commit-hash.outputs.short  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle test and build
        run: ./gradlew build

      - id: commit-hash
        uses: prompt/actions-commit-hash@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ steps.commit-hash.outputs.short }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker-build-push
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}


      - name: Print docker tag
        run: echo 'Docker-tag er ${{ steps.commit-hash.outputs.short }} ' >> $GITHUB_STEP_SUMMARY