name: app-test.yaml

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - build.gradle.kts
      - settings.gradle.kts
      - gradle/**

permissions:
  contents: read

jobs:
  test:
    name: Verify pull request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle test and build
        run: ./gradlew :test :integrationTest --stacktrace