on:
  pull_request:
    paths:
      - src/**
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
      - Dockerfile
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - src/**
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
      - Dockerfile
      - .github/workflows/**


permissions:
  contents: read
  packages: write

jobs:
  test:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/.app-test.yaml
    secrets: inherit

  build:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/.app-build.yaml
    secrets: inherit
