on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    if: github.event_name == 'pull_request'
    name: Verify pull request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle test and build
        run: ./gradlew :test :integrationTest --stacktrace