on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/.test.yaml
    secrets: inherit

  build:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/.build.yaml
    secrets: inherit